### DISCUSSION TITLE
Is it possible to obtain Q_river results in Wflow_sbm by distinguishing contributions from both subsurface flow and overland flow components?

### DISCUSSION THREAD

**Discussion by Safa136** [Deltares/Wflow.jl#334] [Q&A] [answered]
Is it possible, within the Wflow_sbm framework, to derive Q_river results while explicitly separating the contributions of subsurface and overland flow components?

**Comment by verseve** [comment]
Yes, in wflow you can add `lateral.subsurface.to_river` [m3/day] and `lateral.land.to_river` [m3/s] to the TOML file to separate the contribution of subsurface and overland flow to the river flow.

**Comment by Safa136** [comment]
Thank you for your response. I tried to include it as [output.lateral.subsurface.to_river] and then q = "q_subtoriver" , but it doesn't work. can you elaborate more?

**Comment by verseve** [comment]
The following settings should work in the TOML file:

```toml

[output.lateral.land]
to_river = "q_landtoriver"

[output.lateral.subsurface]
to_river = "q_subtoriver"
```
