### DISCUSSION TITLE
How to Show "actual evapotranspiration" and "delta storage" in the output files?

### DISCUSSION THREAD

**Discussion by AldenShadd1000** [Deltares/Wflow.jl#521] [Q&A]
Hello All,

Could you kindly guide me how can I get print of variables like actual evapotranspiration, subsurface storage, surface storage, change in storage, delta storage etc into output.nc file? In fact I would like to calculate the water balance grid by grid.

Thanks

**Comment by vers-w** [comment]
Please find below an example of part of the TOML file to write some of these variables.

You can find more model parameters and variables: 
https://deltares.github.io/Wflow.jl/stable/model_docs/params_vertical/
https://deltares.github.io/Wflow.jl/stable/model_docs/params_lateral/


```toml
[output]
path = "output.nc"

[output.vertical]
actevap= "actevap" # actual evapotranspiration [mm/dt]
satwaterdepth = "satwaterdepth" # saturated store [mm]
ustoredepth = "ustoredepth" # total amount of available water in the unsaturated zone [mm]
total_storage = "total_storage" # total water storage (excluding floodplains, lakes and reservoirs) [mm]

[output.lateral.land]
h = "h_land" # water depth [m] (internal timestep routing (instantaneous))
h_av = "h_av_land" # average water depth [m] during model timestep dt

[output.lateral.river]
h = "h_river"  # water depth [m] (internal timestep routing (instantaneous))
h_av = "h_av_river" # average water depth [m] during model timestep dt
```
