### ISSUE TITLE
Flows to be printed for each grid cell

### ISSUE THREAD

**Issue by mullerrobert799** [Deltares/Wflow.jl#252]
I'd like to print flows for each grid cell. We can do that for gauging stations through CSV directly in *.toml file. Is there any way to get all flow time series for each grid cell? Looking forward!

**Comment by verseve** [comment]
The general approach for this is to write gridded output. For example add this the TOML file to get average river discharge for all cells:

```toml
[output]
path = "output.nc"

[output.lateral.river]
q_av = "q_av_river"
```
You can then postprocess this gridded data with Julia or Python.
