### ISSUE TITLE
ERROR: NetCDF error: NetCDF: Invalid dimension ID or name (NetCDF error code: -46)

### ISSUE THREAD

**Issue by chooron** [Deltares/Wflow.jl#301]
### Wflow version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have checked that this bug exists on the latest version of Wflow.

### Reproducible Example

there is my config file
```
casename = "wflow_sbm"
calendar = "proleptic_gregorian"
starttime = 2018-01-01T10:30:00
endtime = 2018-10-30T10:30:00
time_units = "days since 1900-01-01 00:00:00"
timestepsecs = 86400

[state]
path_input = "instate/instates.nc"
path_output = "run_default/outstate/outstates.nc"

[input]
path_forcing = "inmaps-met_*.nc"
path_static = "staticmaps.nc"
gauges = "wflow_gauges"
ldd = "wflow_ldd"
river_location = "wflow_river"
subcatchment = "wflow_subcatch"
forcing = [ "vertical.precipitation", "vertical.temperature", "vertical.potential_evaporation",]
cyclic = [ "vertical.leaf_area_index",]
gauges_gauge_station = "wflow_gauges_gauge_station"

[model]
type = "sbm"
masswasting = true
snow = true
reinit = true
reservoirs = false
lakes = false
glacier = false
kin_wave_iteration = true
kw_river_tstep = 900
kw_land_tstep = 3600
thicknesslayers = [ 100, 300, 800,]

[output]
path = "run_default/output.nc"

[csv]
path = "run_default/output.csv"
[[csv.column]]
header = "Q"
map = "gauges"
parameter = "lateral.river.q_av"

[[csv.column]]
header = "Q"
map = "gauges_gauge_station"
parameter = "lateral.river.q_av"

[state.vertical]
satwaterdepth = "satwaterdepth"
snow = "snow"
tsoil = "tsoil"
ustorelayerdepth = "ustorelayerdepth"
snowwater = "snowwater"
canopystorage = "canopystorage"

[input.vertical]
altitude = "wflow_dem"
#c = "c"
#cf_soil = "cf_soil"
#cfmax = "Cfmax"
#e_r = "EoverR"
#f = "f"
#infiltcappath = "InfiltCapPath"
#infiltcapsoil = "InfiltCapSoil"
#kext = "Kext"
#"kv₀" = "KsatVer"
leaf_area_index = "LAI"
#m = "M_"
#maxleakage = "MaxLeakage"
#pathfrac = "PathFrac"
potential_evaporation = "pet"
precipitation = "precip"
#rootdistpar = "rootdistpar"
#rootingdepth = "RootingDepth"
#soilminthickness = "SoilMinThickness"
#soilthickness = "SoilThickness"
#specific_leaf = "Sl"
#storage_wood = "Swood"
temperature = "temp"
#tt = "TT"
#tti = "TTI"
#ttm = "TTM"
#water_holding_capacity = "WHC"
#waterfrac = "WaterFrac"
#"θᵣ" = "thetaR"
#"θₛ" = "thetaS"

[state.lateral.river]
q = "q_river"
h = "h_river"
h_av = "h_av_river"

[state.lateral.subsurface]
ssf = "ssf"

[state.lateral.land]
q = "q_land"
h = "h_land"
h_av = "h_av_land"

[input.lateral.river]
length = "wflow_riverlength"
n = "N_River"
slope = "RiverSlope"
width = "wflow_riverwidth"
bankfull_depth = "RiverDepth"

[input.lateral.subsurface]
ksathorfrac = "KsatHorFrac"

[input.lateral.land]
n = "N"
slope = "Slope"

[output.lateral.river]
q_av = "q_river"

[output.lateral.land]
q = "q_land"
h = "h_land"

```
the `inmaps-met_*.nc` is:
```
<xarray.Dataset>
Dimensions:      (time: 122, lat: 410, lon: 315)
Coordinates:
  * time         (time) datetime64[ns] 2017-09-01 2017-09-02 ... 2017-12-31
  * lat          (lat) float64 -17.53 -17.54 -17.55 ... -20.92 -20.93 -20.94
  * lon          (lon) float64 32.38 32.39 32.4 32.4 ... 34.97 34.98 34.99 35.0
Data variables:
    precip       (time, lat, lon) float32 ...
    pet          (time, lat, lon) float32 ...
    temp         (time, lat, lon) float32 ...
    spatial_ref  int32 ...
Attributes:
    standard_name:   precipitation
    units:           mm
    category:        meteo
    paper_doi:       10.1038/sdata.2015.66
    paper_ref:       Funk et al (2015)
    source_license:  CC
    source_url:      https://www.chc.ucsb.edu/data/chirps
    source_version:  v2.0
    _FillValue:      nan
    unit:            mm
    precip_fn:       chirps
```
the static_map is:
```
<xarray.Dataset>
Dimensions:                (lat: 410, lon: 315, time: 12)
Coordinates:
  * lat                    (lat) float64 -17.53 -17.54 -17.55 ... -20.93 -20.94
  * lon                    (lon) float64 32.38 32.39 32.4 ... 34.98 34.99 35.0
  * time                   (time) int32 1 2 3 4 5 6 7 8 9 10 11 12
    spatial_ref            int32 ...
Data variables: (12/47)
    wflow_ldd              (lat, lon) float32 ...
    wflow_subcatch         (lat, lon) float64 ...
    wflow_uparea           (lat, lon) float64 ...
    wflow_streamorder      (lat, lon) float32 ...
    subare                 (lat, lon) float32 ...
    wflow_dem              (lat, lon) float32 ...
    ...                     ...
    WHC                    (lat, lon) float32 ...
    G_Cfmax                (lat, lon) float32 ...
    G_SIfrac               (lat, lon) float32 ...
    G_TT                   (lat, lon) float32 ...
    wflow_gauges_sfincs    (lat, lon) float64 ...
    wflow_subcatch_sfincs  (lat, lon) float64 ...
```

### Current behaviour

When I run this file, the error raised:
```
[ Info: Wflow version `v0.7.1`
[ Info: Initialize model variables for model type `sbm`.
[ Info: Cyclic parameters are provided by `models\wflow\staticmaps.nc`.
[ Info: Forcing parameters are provided by `models\wflow\inmaps-met_*.nc`.
┌ Error: Wflow simulation failed
│   exception =
│    NetCDF error: Variable 'time' not found in file models\wflow\staticmaps.nc (NetCDF error code: -49)
│    Stacktrace:
│      [1] nc_inq_varid(ncid::Int32, name::String)
│        @ NCDatasets C:\Users\svc-teamcity-ansible\.julia\packages\NCDatasets\st9Jz\src\netcdf_c.jl:1508
│      [2] _variable
│        @ C:\Users\svc-teamcity-ansible\.julia\packages\NCDatasets\st9Jz\src\variable.jl:72 [inlined]
│      [3] variable
│        @ C:\Users\svc-teamcity-ansible\.julia\packages\NCDatasets\st9Jz\src\variable.jl:83 [inlined]
│      [4] cfvariable(ds::NCDatasets.NCDataset{Nothing}, varname::String)
│        @ CommonDataModel C:\Users\svc-teamcity-ansible\.julia\packages\CommonDataModel\RSBF3\src\cfvariable.jl:94
│      [5] getindex
│        @ C:\Users\svc-teamcity-ansible\.julia\packages\NCDatasets\st9Jz\src\cfvariable.jl:311 [inlined]
│      [6] prepare_reader(config::Wflow.Config)
│        @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\io.jl:700
│      [7] initialize_sbm_model(config::Wflow.Config)
│        @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\sbm_model.jl:15
│      [8] run(config::Wflow.Config)
│        @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:183
│      [9] (::Wflow.var"#229#230"{IOStream, Bool, Wflow.Config})()
│        @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:162
│     [10] with_logstate(f::Function, logstate::Any)
│        @ Base.CoreLogging .\logging.jl:514
│     [11] with_logger
│        @ .\logging.jl:626 [inlined]
│     [12] run(tomlpath::String; silent::Nothing)
│        @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:158
│     [13] run
│        @ C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:150 [inlined]
│     [14] julia_main()
│        @ wflow_cli D:\buildAgent\work\44830c4db5199711\src\wflow_cli.jl:22
│     [15] top-level scope
│        @ none:1
└ @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:169

```

### Desired behaviour

I'm using the watershed I researched based on the project, and when I configure the wflow input file using hydromt and run julia I get this error

**Comment by verseve** [comment]
The input files look correct and staticmaps.nc has a `time` coordinate.  Could you please share your model setup, so we can look into this issue in more detail?

**Comment by JoostBuitink** [comment]
I see that you also commented out quite some lines in the `[input.vertical]` section (the lines starting with a `#`). Could it be related to this?

**Comment by chooron** [comment]
> The input files look correct and staticmaps.nc has a `time` coordinate. Could you please share your model setup, so we can look into this issue in more detail?

By debugging julia I found the cause of the problem to be line 407-415 in "sbm.jl":
c = ncread(
    nc,
    config,
    "vertical.c";
    sel = inds,
    defaults = 10.0,
    type = Float,
    dimname = :layer,
)
At the moment, due to insufficient data collection, I can only set c by default, but this error occurs in this statement.
I solved the problem temporarily by modifying staticmap:
```
c_arr = np.ones((4, 137, 138)) * 10
static['c'] = xr.Variable(dims={'layer': 4, 'lat': 137, 'lon': 138}, data=c_arr)
```
But other problems arose today:
```
ERROR: arrays contains missing values (values equal to the fill values attribute in the NetCDF file)
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] nomissing(da::Vector{Union{Missing, Float32}})
    @ NCDatasets C:\Users\svc-teamcity-ansible\.julia\packages\NCDatasets\st9Jz\src\variable.jl:272
  [3] ncread(nc::NCDatasets.NCDataset{Nothing}, config::Wflow.Config, parameter::String; alias::Nothing, optional::Bool, sel::Vector{CartesianIndex{2}}, defaults::Nothing, type::Type, allow_missing::Bool, fill::Nothing, dimname::Nothing)
    @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\utils.jl:320
  [4] initialize_sbm_model(config::Wflow.Config)
    @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\sbm_model.jl:106
  [5] run(config::Wflow.Config)
    @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:183
  [6] (::Wflow.var"#229#230"{IOStream, Bool, Wflow.Config})()
    @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:162
  [7] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging .\logging.jl:514
  [8] with_logger
    @ .\logging.jl:626 [inlined]
  [9] run(tomlpath::String; silent::Nothing)
    @ Wflow C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:158
 [10] run
    @ C:\Users\svc-teamcity-ansible\.julia\packages\Wflow\0nr8S\src\Wflow.jl:150 [inlined]
 [11] julia_main()
    @ wflow_cli D:\buildAgent\work\44830c4db5199711\src\wflow_cli.jl:22
 [12] top-level scope
    @ none:1
```
The slope data is prepared by following [prepare_ldd.ipynb](https://deltares.github.io/hydromt_wflow/latest/_examples/prepare_ldd.html)

finally, the below is my model config file:
```
gauge_points:
  data_type: GeoDataFrame
  path: D:\code\py\pycharm\Group Project\hydromt_wflow_learn\data\lintao_data\lintao_static\geojson\gauge_points.geojson
  driver: vector
  filesystem: local
  kwargs:
    assert_gtype: Point
  crs: 4326
lintao_static:
  data_type: RasterDataset
  path: D:\code\py\pycharm\Group Project\hydromt_wflow_learn\data\lintao_data\lintao_static\processed\{variable}.tif
  driver: raster
  filesystem: local
  crs: 4326
  rename:
    slope: lndslp
  meta:
    category: topography
    paper_doi: 10.5194/hess-2020-582
    paper_ref: Eilander et al. (2021)
    source_license: ODC-By 1.0
    source_url: https://zenodo.org/record/5166932#.YVbxJ5pByUk
    source_doi: 10.5281/zenodo.5166932
    source_version: 1.0
modis_lai:
  data_type: RasterDataset
  path: D:\code\py\pycharm\Group Project\hydromt_wflow_learn\data\lintao_data\lintao_static\modis_lai.nc
  driver: raster
  filesystem: local
  crs: 4326
  unit_mult:
    LAI: 0.1
  meta:
    category: landuse
    notes: this dataset has been extracted from GEE ('MODIS/006/MCD15A3H') for the
      period '2003-01-01', '2017-12-31'
    paper_doi: 10.5067/MODIS/MCD15A3H.006
    paper_ref: Myneni et al (2015)
    source_license: https://lpdaac.usgs.gov/data/data-citation-and-policies/
    source_url: https://lpdaac.usgs.gov/products/mcd15a3hv006/
    source_version: MCD15A3H V006
rivers_shp:
  data_type: GeoDataFrame
  path: D:\code\py\pycharm\Group Project\hydromt_wflow_learn\data\lintao_data\lintao_static\geojson\river_shp.gpkg
  driver: vector
  filesystem: local
  rename:
    Q2: qbankfull
    width_m: rivwth
  meta:
    category: hydrography
    paper_doi: 10.5281/zenodo.3552776
    paper_ref: Lin et al. (2019)
    source_license: CC-BY-NC 4.0
    source_url: https://zenodo.org/record/3552776#.YVbOrppByUk
    source_version: 1
```
